/*
  Auto-generated by: https://github.com/pmndrs/gltfjsx
  Author: wallmasterr (https://sketchfab.com/wallmasterr)
  License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
  Source: https://sketchfab.com/3d-models/tenhun-falling-spaceman-fanart-9fd80b6a259f41fd99e6f56eee686dc5
  Title: Tenhun Falling spaceman (FanArt)

  Phase 1 optimisations applied:
  - Draco compression via useGLTF with draco path
  - All THREE.Material / THREE.Color instances moved into useMemo → zero GC per-frame
  - envMap only created when NOT in low-perf mode
  - animations started in useEffect with correct deps
*/

import React, { useEffect, useRef, useMemo } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { useSpring, a } from '@react-spring/three';
import { useFrame } from '@react-three/fiber';
import * as THREE from 'three';

// Draco decoder lives in the public folder (copied from node_modules/three/examples/jsm/libs/draco)
const DRACO_PATH = '/draco/';
const MODEL_PATH = '/models/tenhun_falling_spaceman_fanart.glb';

export function Astronaut({ isLowPerf = false, ...props }) {
  const group = useRef();

  // ── Draco-enabled loader ─────────────────────────────────────────────────
  const { nodes, materials, animations } = useGLTF(MODEL_PATH, DRACO_PATH);
  const { actions } = useAnimations(animations, group);

  // ── Shared envMap (memoised – created exactly once, never inside render) ─
  const envMap = useMemo(() => {
    if (isLowPerf) return null; // skip on low-end GPUs
    return new THREE.CubeTextureLoader().setPath('/envmaps/').load([
      'px.jpg', 'nx.jpg',
      'py.jpg', 'ny.jpg',
      'pz.jpg', 'nz.jpg',
    ]);
  }, [isLowPerf]);

  // ── Material palette (memoised – never recreated between renders) ─────────
  const mats = useMemo(() => {
    const shared = isLowPerf
      ? {}
      : { envMap, envMapIntensity: 0.7 };

    const baseSuit = new THREE.MeshStandardMaterial({
      color: '#ffffff',
      roughness: 0.6,
      metalness: 0.2,
      ...shared,
    });
    const orangeAccent = new THREE.MeshStandardMaterial({
      color: '#ff7f2a',
      roughness: 0.4,
      metalness: 0.4,
      ...shared,
      envMapIntensity: isLowPerf ? undefined : 0.8,
    });
    const blueAccent = new THREE.MeshStandardMaterial({
      color: '#1a237e',
      roughness: 0.5,
      metalness: 0.3,
      ...shared,
    });
    const redLining = new THREE.MeshStandardMaterial({
      color: '#d32f2f',
      roughness: 0.4,
      metalness: 0.3,
      ...shared,
    });
    const glovesOrange = new THREE.MeshStandardMaterial({
      color: '#ff7f2a',
      roughness: 0.5,
      metalness: 0.3,
      ...shared,
    });
    const glovesBlue = new THREE.MeshStandardMaterial({
      color: '#1a237e',
      roughness: 0.5,
      metalness: 0.3,
      ...shared,
    });
    const controlBox = new THREE.MeshStandardMaterial({
      color: '#e0e0e0',
      roughness: 0.3,
      metalness: 0.5,
      emissive: new THREE.Color('#ffd700'),
      emissiveIntensity: isLowPerf ? 0.5 : 1.5,
      ...shared,
      envMapIntensity: isLowPerf ? undefined : 0.8,
    });
    const backpack = new THREE.MeshStandardMaterial({
      color: '#ff7f2a',
      roughness: 0.5,
      metalness: 0.3,
      ...shared,
    });
    const backpackWhite = new THREE.MeshStandardMaterial({
      color: '#ffffff',
      roughness: 0.6,
      metalness: 0.2,
      ...shared,
    });

    // Visor uses MeshPhysicalMaterial – skip on low-perf to avoid extra shader complexity
    const visor = isLowPerf
      ? new THREE.MeshStandardMaterial({ color: '#2a1a3c', roughness: 0.2, metalness: 0.8 })
      : new THREE.MeshPhysicalMaterial({
          color: '#2a1a3c',
          roughness: 0.1,
          metalness: 1.0,
          clearcoat: 1.0,
          clearcoatRoughness: 0.05,
          reflectivity: 1.0,
          transmission: 0.2,
          thickness: 0.5,
          sheen: new THREE.Color(0xffd700),
          sheenRoughness: 0.2,
          envMap,
          envMapIntensity: 1.2,
        });

    return { baseSuit, orangeAccent, blueAccent, redLining, glovesOrange, glovesBlue, controlBox, backpack, backpackWhite, visor };
  }, [envMap, isLowPerf]); // eslint-disable-line react-hooks/exhaustive-deps

  // ── Dispose materials when component unmounts ────────────────────────────
  useEffect(() => {
    return () => {
      Object.values(mats).forEach((m) => m?.dispose());
      envMap?.dispose();
    };
  }, [mats, envMap]);

  // ── Start animation clip ─────────────────────────────────────────────────
  useEffect(() => {
    if (animations.length > 0) {
      actions[animations[0].name]?.play();
    }
  }, [actions, animations]);

  // ── Cinematic Spring Fall ────────────────────────────────────────────────
  const targetPos = props.position ?? [1.3, -1, 0];
  const { springY } = useSpring({
    from: { springY: targetPos[1] + 15 }, // Start high above
    to: { springY: targetPos[1] },
    config: { mass: 2, tension: 80, friction: 15 }, // Bouncy, heavy fall
  });

  return (
    <a.group position-y={springY} position-x={targetPos[0]} position-z={targetPos[2]}>
      {/* Lighting – ambient kept low, key/fill directionals do the work */}
      <ambientLight intensity={isLowPerf ? 0.8 : 0.5} />
      <directionalLight
        position={[8, 15, 10]}
        intensity={isLowPerf ? 0.8 : 1.2}
        color="#ffb347"
        castShadow={!isLowPerf}
      />
      <directionalLight
        position={[-10, 5, -10]}
        intensity={0.5}
        color="#b3c6ff"
      />

      <group
        ref={group}
        {...props}
        position={[0, 0, 0]} // Position handled by parent a.group
        dispose={null}
        rotation={[-Math.PI / 2, -0.2, 2.2]}
        scale={props.scale ?? 0.3}
      >
        <group name="Sketchfab_Scene">
          <group name="Sketchfab_model">
            <group name="Root">
              <group name="metarig">
                <primitive object={nodes.metarig_rootJoint} />

                {nodes.Cube001_0?.geometry && (
                  <skinnedMesh name="Cube001_0" geometry={nodes.Cube001_0.geometry}
                    material={mats.baseSuit} skeleton={nodes.Cube001_0.skeleton} />
                )}
                {nodes.Cube005_0?.geometry && (
                  <skinnedMesh name="Cube005_0" geometry={nodes.Cube005_0.geometry}
                    material={mats.blueAccent} skeleton={nodes.Cube005_0.skeleton} />
                )}
                {nodes.Cube002_0?.geometry && (
                  <skinnedMesh name="Cube002_0" geometry={nodes.Cube002_0.geometry}
                    material={mats.blueAccent} skeleton={nodes.Cube002_0.skeleton} />
                )}
                {nodes.Plane_0?.geometry && (
                  <skinnedMesh name="Plane_0" geometry={nodes.Plane_0.geometry}
                    material={mats.visor} skeleton={nodes.Plane_0.skeleton} />
                )}
                {nodes.Cube008_0?.geometry && (
                  <skinnedMesh name="Cube008_0" geometry={nodes.Cube008_0.geometry}
                    material={mats.orangeAccent} skeleton={nodes.Cube008_0.skeleton} />
                )}
                {nodes.Cube004_0?.geometry && (
                  <skinnedMesh name="Cube004_0" geometry={nodes.Cube004_0.geometry}
                    material={mats.glovesOrange} skeleton={nodes.Cube004_0.skeleton} />
                )}
                {nodes.Cube003_0?.geometry && (
                  <skinnedMesh name="Cube003_0" geometry={nodes.Cube003_0.geometry}
                    material={mats.glovesBlue} skeleton={nodes.Cube003_0.skeleton} />
                )}
                {nodes.Cube_0?.geometry && (
                  <skinnedMesh name="Cube_0" geometry={nodes.Cube_0.geometry}
                    material={mats.baseSuit} skeleton={nodes.Cube_0.skeleton} />
                )}
                {nodes.Cube009_0?.geometry && (
                  <skinnedMesh name="Cube009_0" geometry={nodes.Cube009_0.geometry}
                    material={mats.backpack} skeleton={nodes.Cube009_0.skeleton} />
                )}
                {nodes.Cube011_0?.geometry && (
                  <skinnedMesh name="Cube011_0" geometry={nodes.Cube011_0.geometry}
                    material={mats.backpackWhite} skeleton={nodes.Cube011_0.skeleton} />
                )}
              </group>
            </group>
          </group>
        </group>
      </group>
    </a.group>
  );
}

// Preload with Draco path – called at module level so Next/Vite can tree-shake it
useGLTF.preload(MODEL_PATH, DRACO_PATH);
