/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: wallmasterr (https://sketchfab.com/wallmasterr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tenhun-falling-spaceman-fanart-9fd80b6a259f41fd99e6f56eee686dc5
Title: Tenhun Falling spaceman (FanArt)
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useMotionValue, useSpring } from "framer-motion";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

export function Astronaut(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/tenhun_falling_spaceman_fanart.glb"
  );
  const { actions } = useAnimations(animations, group);

  // Load environment map for reflections
  const envMap = new THREE.CubeTextureLoader().setPath("/envmaps/").load([
    "px.jpg",
    "nx.jpg",
    "py.jpg",
    "ny.jpg",
    "pz.jpg",
    "nz.jpg",
  ]);

  useEffect(() => {
    // Prevent state updates during render phase
    if (animations.length > 0) {
      actions[animations[0].name]?.play();
    }
  }, [actions, animations]);

  // --- MATERIALS FOR DETAILED COLOR BLOCKING ---
  const baseSuitMaterial = new THREE.MeshStandardMaterial({
    color: "#ffffff", // bright white
    roughness: 0.6,
    metalness: 0.2,
    envMap: envMap,
    envMapIntensity: 0.7,
  });
  const orangeAccentMaterial = new THREE.MeshStandardMaterial({
    color: "#ff7f2a", // vibrant orange (shoulders, knees, boots, pipes)
    roughness: 0.4,
    metalness: 0.4,
    envMap: envMap,
    envMapIntensity: 0.8,
  });
  const blueAccentMaterial = new THREE.MeshStandardMaterial({
    color: "#1a237e", // deep navy blue (inner thighs, gloves, boot tops)
    roughness: 0.5,
    metalness: 0.3,
    envMap: envMap,
    envMapIntensity: 0.7,
  });
  const redLiningMaterial = new THREE.MeshStandardMaterial({
    color: "#d32f2f", // red lining (seams, compartments)
    roughness: 0.4,
    metalness: 0.3,
    envMap: envMap,
    envMapIntensity: 0.7,
  });
  const glovesOrangeMaterial = new THREE.MeshStandardMaterial({
    color: "#ff7f2a", // orange cuffs
    roughness: 0.5,
    metalness: 0.3,
    envMap: envMap,
    envMapIntensity: 0.7,
  });
  const glovesBlueMaterial = new THREE.MeshStandardMaterial({
    color: "#1a237e", // blue fingertips
    roughness: 0.5,
    metalness: 0.3,
    envMap: envMap,
    envMapIntensity: 0.7,
  });
  const controlBoxMaterial = new THREE.MeshStandardMaterial({
    color: "#e0e0e0",
    roughness: 0.3,
    metalness: 0.5,
    emissive: "#ffd700", // glowing yellow light
    emissiveIntensity: 1.5,
    envMap: envMap,
    envMapIntensity: 0.8,
  });
  const backpackMaterial = new THREE.MeshStandardMaterial({
    color: "#ff7f2a", // orange for backpack
    roughness: 0.5,
    metalness: 0.3,
    envMap: envMap,
    envMapIntensity: 0.7,
  });
  const backpackWhiteMaterial = new THREE.MeshStandardMaterial({
    color: "#ffffff", // white for backpack
    roughness: 0.6,
    metalness: 0.2,
    envMap: envMap,
    envMapIntensity: 0.7,
  });
  // Visor: bluish-purple reflective with orange outline
  const visorMaterial = new THREE.MeshPhysicalMaterial({
    color: "#2a1a3c", // bluish-purple tint
    roughness: 0.1,
    metalness: 1.0,
    clearcoat: 1.0,
    clearcoatRoughness: 0.05,
    reflectivity: 1.0,
    transmission: 0.2,
    thickness: 0.5,
    sheen: new THREE.Color(0xffd700), // gold sheen
    sheenRoughness: 0.2,
    envMap: envMap,
    envMapIntensity: 1.2,
  });
  // Orange outline for visor (approximate with a torus geometry overlay if possible)
  // ... existing code ...
  return (
    <>
      {/* Add lights for realistic rendering */}
      <ambientLight intensity={0.5} />
      {/* Warm orange/yellow key light from upper right */}
      <directionalLight
        position={[8, 15, 10]}
        intensity={1.2}
        color={"#ffb347"}
        castShadow
      />
      {/* Soft blue fill light from left/back */}
      <directionalLight
        position={[-10, 5, -10]}
        intensity={0.5}
        color={"#b3c6ff"}
      />
      <group
        ref={group}
        {...props}
        dispose={null}
        rotation={[-Math.PI / 2, -0.2, 2.2]}
        scale={props.scale || 0.3}
        position={props.position || [1.3, -1, 0]}
      >
        <group name="Sketchfab_Scene">
          <group name="Sketchfab_model">
            <group name="Root">
              <group name="metarig">
                <primitive object={nodes.metarig_rootJoint} />
                {/* --- Mesh-to-body-part mapping comments --- */}
                {/* Main suit (white) */}
                <skinnedMesh
                  name="Cube001_0"
                  geometry={nodes.Cube001_0.geometry}
                  material={baseSuitMaterial}
                  skeleton={nodes.Cube001_0.skeleton}
                />
                {/* Blue accent (arms/legs/shoulders) */}
                <skinnedMesh
                  name="Cube005_0"
                  geometry={nodes.Cube005_0.geometry}
                  material={blueAccentMaterial}
                  skeleton={nodes.Cube005_0.skeleton}
                />
                {/* Blue accent (inner thighs, gloves, boot tops) */}
                <skinnedMesh
                  name="Cube002_0"
                  geometry={nodes.Cube002_0.geometry}
                  material={blueAccentMaterial}
                  skeleton={nodes.Cube002_0.skeleton}
                />
                {/* Visor (bluish-purple, reflective) */}
                <skinnedMesh
                  name="Plane_0"
                  geometry={nodes.Plane_0.geometry}
                  material={visorMaterial}
                  skeleton={nodes.Plane_0.skeleton}
                />
                {/* Orange accent (shoulders, knees, boots, pipes/buttons) */}
                <skinnedMesh
                  name="Cube008_0"
                  geometry={nodes.Cube008_0.geometry}
                  material={orangeAccentMaterial}
                  skeleton={nodes.Cube008_0.skeleton}
                />
                {/* Gloves/boots (orange cuffs) */}
                <skinnedMesh
                  name="Cube004_0"
                  geometry={nodes.Cube004_0.geometry}
                  material={glovesOrangeMaterial}
                  skeleton={nodes.Cube004_0.skeleton}
                />
                {/* Gloves/boots (blue fingertips) */}
                <skinnedMesh
                  name="Cube003_0"
                  geometry={nodes.Cube003_0.geometry}
                  material={glovesBlueMaterial}
                  skeleton={nodes.Cube003_0.skeleton}
                />
                {/* Main suit (white, chest unit) */}
                <skinnedMesh
                  name="Cube_0"
                  geometry={nodes.Cube_0.geometry}
                  material={baseSuitMaterial}
                  skeleton={nodes.Cube_0.skeleton}
                />
                {/* Backpack (orange) */}
                <skinnedMesh
                  name="Cube009_0"
                  geometry={nodes.Cube009_0.geometry}
                  material={backpackMaterial}
                  skeleton={nodes.Cube009_0.skeleton}
                />
                {/* Backpack (white) */}
                <skinnedMesh
                  name="Cube011_0"
                  geometry={nodes.Cube011_0.geometry}
                  material={backpackWhiteMaterial}
                  skeleton={nodes.Cube011_0.skeleton}
                />
                {/* --- Placeholders for red lining, control box, flag/logo --- */}
                {/* If mesh allows, add redLiningMaterial to seams/compartments, controlBoxMaterial to left forearm box, and use a Decal or texture for flag/logo on chest. */}
              </group>
            </group>
          </group>
        </group>
      </group>
    </>
  );
}

useGLTF.preload("/models/tenhun_falling_spaceman_fanart.glb");
